In [31]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [32]:
df=pd.read_csv('Dataset 2 (1).csv')
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [33]:
print(df.columns)
print(df.shape)

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')
(750, 10)

In [34]:
numerical_features=df.select_dtypes(include=['int64','float64']).columns
categorical_features=df.select_dtypes(include=['object']).columns
print(numerical_features)
print(categorical_features)

Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

In [35]:
print("Missing values")
print(df.isnull().sum())

Missing values
UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

In [36]:
print(df['Age'].mean())

41.824

In [37]:
print(df['WatchHoursPerWeek'].mean())

14.236

In [38]:
print(df['MonthlySpend'].mean())

689.9053333333334

In [39]:
df['SubscriptionType'].value_counts()

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [40]:
renewed_users=(df['SubscriptionRenewed']==1).sum()
total_users=len(df)
renewal_percentage=renewed_users/total_users*100
print(renewal_percentage)

0.0

In [41]:
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['SubscriptionType']=le.fit_transform(df['SubscriptionType'])
df['FavoriteGenre']=le.fit_transform(df['FavoriteGenre'])
df['SubscriptionRenewed']=le.fit_transform(df['SubscriptionRenewed'])

In [42]:
X=df.drop(['SubscriptionRenewed','UserID'],axis=1)
y=df['SubscriptionRenewed']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
dt_model=DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train,y_train)
y_pred=dt_model.predict(X_test)
dt_accuracy=accuracy_score(y_test,y_pred)
print(dt_accuracy)
print(confusion_matrix(y_test,y_pred))

(600, 8)
(150, 8)
0.56
[[48 34]
 [32 36]]

In [43]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
knn_accuracy=accuracy_score(y_test,y_pred)
print(knn_accuracy)
if knn_accuracy>dt_accuracy:
    print("knn performs better")
elif knn_accuracy<dt_accuracy:
    print("dt performs better")
else:
    print("both perform equally")

0.6333333333333333
knn performs better

In [44]:
X_reg=df.drop(['MonthlySpend','UserID'],axis=1)
Y_reg=df['MonthlySpend']
X_train_reg, X_test_reg, Y_train_reg, Y_test_reg=train_test_split(X_reg,Y_reg,test_size=0.2, random_state=42)
lr_model=LinearRegression()
lr_model.fit(X_train_reg,Y_train_reg)

LinearRegression()

In [45]:
new_user=[30,1,2,20,3,1,5,1]
predicted_spend=lr_model.predict([new_user])
print(predicted_spend[0])

1339.5029186555455

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(